Add Verse (Bitcoin.com) to Projects
duneanalytics/projects pull request #179
Opened 2023-05-05 06:15 UTC by lizzydude90

2023-05-05 09:37 UTC, 0xBoxer commented
@philippWassibauer would appreciate a review

2023-05-05 09:54 UTC, philippWassibauer requested changes
if the embed is fixed this is good to go.

2023-05-05 09:54 UTC, philippWassibauer commented on pages/verse/verse.md
> +    link: "https://dune.com/queries/1942119/3204019"
this needs to be an embed, eg: 
`https://dune.com/embeds/31193/62877/a7284a40-96e1-484b-a99b-cc00c25f16b5`

2023-05-05 09:56 UTC, philippWassibauer approved these changes

2023-05-05 09:56 UTC, philippWassibauer commented on pages/verse/verse.md
> +    link: "https://dune.com/queries/1942119/3204019"
```suggestion
    link: "https://dune.com/embeds/1942119/3204019" 
```

2023-05-05 09:56 UTC, merged

2023-05-12 11:47 UTC, philippWassibauer commented
@0xBoxer @lizzydude90 I had to remove the embed, as it broke the page. You need to add the secret to the embed, like so: 

https://dune.com/embeds/2452344/4031032/4b581815-f7ec-485f-8c4e-9556c5a05eb2

Easiest done by creating a private query and then clicking embed. Please submit another PR to fix this.

2023-05-12 14:26 UTC, lizzydude90 commented
Thanks Phillip,

We're going to submit another update next week to include the latest
suggestions, will include your suggestions. Much appreciated.

Have a good weekend,

On Fri, 12 May 2023, 20:47 Philipp Wassibauer, ***@***.***>
wrote:

> @0xBoxer <https://github.com/0xBoxer> @lizzydude90
> <https://github.com/lizzydude90> I had to remove the embed, as it broke
> the page. You need to add the secret to the embed, like so:
>
>
> https://dune.com/embeds/2452344/4031032/4b581815-f7ec-485f-8c4e-9556c5a05eb2
>
> Easiest done by creating a private query and then clicking embed. Please
> submit another PR to fix this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/duneanalytics/projects/pull/179#issuecomment-1545617727>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEJAWNM4K645DGPSXISHQN3XFYPOXANCNFSM6AAAAAAXWV6XWI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>