add StaFi
duneanalytics/projects pull request #183
Opened 2023-05-15 08:14 UTC by signalxu

[Twitter Announcement](https://twitter.com/StaFi_Protocol/status/1654828801568931841)
[Dune profile](dune.com/stafi-analysis)

2023-05-17 08:38 UTC, philippWassibauer approved these changes

2023-05-17 08:39 UTC, philippWassibauer requested changes
the embeds are done wrong, they should follow the pattern of
https://dune.com/embeds/31193/62877/a7284a40-96e1-484b-a99b-cc00c25f16b5

2023-05-17 11:37 UTC, signalxu commented
> the embeds are done wrong, they should follow the pattern of https://dune.com/embeds/31193/62877/a7284a40-96e1-484b-a99b-cc00c25f16b5

<img width="786" alt="image" src="https://github.com/duneanalytics/projects/assets/10573459/77934409-2cf7-4116-bc78-7192a97ed6cd">

but when i click the embed button, the url is `https://dune.com/embeds/2381080/3905179`

2023-05-17 13:02 UTC, signalxu commented
> the embeds are done wrong, they should follow the pattern of https://dune.com/embeds/31193/62877/a7284a40-96e1-484b-a99b-cc00c25f16b5

Thanks, i have fixed it.

2023-05-18 14:18 UTC, philippWassibauer approved these changes

2023-05-18 14:18 UTC, merged